name: Regression Tests
on: [push]
jobs:
  regression-tests:
    strategy:
      matrix:
        #mpi: [mpich, openmpi]
        #python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        mpi: [mpich]
        python-version: [3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $PWD
      - run: ls -l
      - name: Build ${{ matrix.MPI }}
        run: bash ./.github/scripts/install-mpi.sh ${{ matrix.MPI }}
      - name: Verify env
        run: |
          export PATH=$(pwd)/${MPI}/bin:${PATH}
          export LD_LIBRARY_PATH=$(pwd)/${MPI}/lib:${LD_LIBRARY_PATH}
          env
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - name: Install Requirements
        run: |
          export PATH=$(pwd)/${MPI}/bin:${PATH}
          export LD_LIBRARY_PATH=$(pwd)/${MPI}/lib:${LD_LIBRARY_PATH}
          pip install -r requirements.txt
      - name: Install Pyranda
        run: |
          export PATH=$(pwd)/${MPI}/bin:${PATH}
          export LD_LIBRARY_PATH=$(pwd)/${MPI}/lib:${LD_LIBRARY_PATH}
          python setup.py build
          python setup.py install
        env:
      - name: Run Regression Tests
        run: cd tests && python run_tests.py 1